config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'ideas#index'

  resources :ideas

  get 'about' => 'static_pages#about'
  get 'random' => 'static_pages#random'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    validates :description, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    def index
        @ideas = Idea.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
    end

    def create
        @idea = Idea.create(idea_params)
        if @idea.valid?
            flash[:success] = "Your idea has been posted!"
        else
            flash[:alert] = "Woops! Looks like there has been an error!"
        end
        redirect_to root_path
      end

      def edit
        @idea = Idea.find(params[:id])
      end

      def update
        @idea = Idea.find(params[:id])
        if @idea.update(idea_params)
          flash[:success] = "The idea has been updated!"
          redirect_to root_path
        else
          flash[:alert] = "Woops! Looks like there has been an error!"
          redirect_to edit_idea_path(params[:id])
        end
      end

      def destroy
        @idea = Idea.find(params[:id])
        @idea.destroy
        flash[:success] = "The idea was successfully deleted!"
        redirect_to root_path
     end
    
      private
    
      def idea_params
        params.require(:idea).permit(:description, :author)
    end

     
end

# crud
# create, read, update, destroy

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def about
    end

    def random
        @idea = Idea.order("RANDOM()").first
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ideas/edit.html.erb
<h1>Revise Idea</h1>

<%= simple_form_for @idea, method: :patch do |f| %>
    <%= f.input :description %>
    <%= f.input :author %>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>

app/views/ideas/index.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <%= simple_form_for Idea.new do |f| %>
        <%= f.input :description %>
        <%= f.input :author %>
        
     
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>




<% @ideas.each do |idea| %>
    <div class="card">
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p class= "description"><%= idea.description %></p>
                <footer class="blockquote-footer">by <%= idea.author %></footer>
            </blockquote>
            <br>

            <div class="btn-group" role="group">
                <%= link_to 'Delete', idea_path(idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
                <%= link_to 'Revise', edit_idea_path(idea), class: 'btn btn-sm btn-success' %>
            </div>
        </div>
    </div>
<% end %>

<div class="d-flex justify-content-center">
    <%= will_paginate @ideas %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>  
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@300;400;600;700&family=Open+Sans:wght@300;400;600;700&family=Pacifico&display=swap" rel="stylesheet">
      </head>

  <body>
   <div id = "wrap">
   <%= render 'shared/nav' %>

  

   <div class = "container">
   <div class = "row">
   <div class = "col-xs-12 col-md-6 col-md-offset-3">
   <%= render 'shared/flash_messages' %>
    <%= yield %>
    </div>
    </div>
    </div>

    </div><!-- wrap -->

    <div class="footer text-center">
    <p>&copy; TECHBRAIN <%= Date.today.year %> All Right Reserved</p>
    </div>

  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <% if message_type == "notice" %>
      <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
    <% elsif message_type == "alert" %>
      <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
    <% else %>
      <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
    <% end %>
  <% end %>
  

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg  bg-light">
<div class="container-fluid">
<a class="navbar-brand" href="/">Ideator</a>
<div class= "d-inline-flex justify-content-end">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
    <li class="nav-item">
    <%= link_to "All Ideas", root_path, class: "nav-link" %>
      
    </li>
    <li class="nav-item">
    <%= link_to "Inspire Me", random_path, class: "nav-link" %>
    
    </li>
    <li class="nav-item">
    <%= link_to "About",  about_path, class: "nav-link" %>
      
    </li>
  </ul>
</div>
</div>
</div>
</nav>

app/views/static_pages/about.html.erb
<div class="description">
<h1>About</h1>

<h4>Share your ideas with the world and find others.</h4>

<p>
Once you are familiar with Ruby, you can now begin to learn Rails! Many new developers are asking the point of learning Ruby on Rails if there are other frameworks. The answer is simply that this web application framework can be an ideal solution for startups because of its numerous functions that come out of the box and its speed of deployment and scalability. Let’s look at what educational tools can assist you in learning Ruby on Rails online and the books you need to study to learn the essentials of RoR.
<p>

<h5>Be an excellent Rubyist</h5>
<p>
It is important not to underestimate the importance of the books you read when studying programming. Despite the rapid growth of technology and programming, the best programming books remain current and are regularly updated with the release of new versions and updates. 
</div>

app/views/static_pages/random.html.erb
<% if @idea.present? %>
  <%= link_to 'Inspire Me', random_path, class: 'btn btn-primary btn-block' %>

  <div class="card">
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p class="description"><%= @idea.description %></p>
        <footer class="blockquote-footer">by <%= @idea.author %></footer>
      </blockquote>
      <br>
      <div class="btn-group" role="group">
        <%= link_to 'Delete', idea_path(@idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
        <%= link_to 'Revise', edit_idea_path(@idea), class: 'btn btn-sm btn-success' %>
      </div>
    </div>
  </div>
<% end %>